/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstallaRouteImport } from './routes/installa'
import { Route as ApiMacAppRouteImport } from './routes/api/mac-app'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallaRoute = InstallaRouteImport.update({
  id: '/installa',
  path: '/installa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMacAppRoute = ApiMacAppRouteImport.update({
  id: '/api/mac-app',
  path: '/api/mac-app',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/installa': typeof InstallaRoute
  '/api/mac-app': typeof ApiMacAppRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/installa': typeof InstallaRoute
  '/api/mac-app': typeof ApiMacAppRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/installa': typeof InstallaRoute
  '/api/mac-app': typeof ApiMacAppRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/installa' | '/api/mac-app'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/installa' | '/api/mac-app'
  id: '__root__' | '/' | '/installa' | '/api/mac-app'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstallaRoute: typeof InstallaRoute
  ApiMacAppRoute: typeof ApiMacAppRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installa': {
      id: '/installa'
      path: '/installa'
      fullPath: '/installa'
      preLoaderRoute: typeof InstallaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mac-app': {
      id: '/api/mac-app'
      path: '/api/mac-app'
      fullPath: '/api/mac-app'
      preLoaderRoute: typeof ApiMacAppRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstallaRoute: InstallaRoute,
  ApiMacAppRoute: ApiMacAppRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
